server:
  port: 8081

spring:
  application:
    name: ytdlp
  datasource:
    password: password
    username: dcat
    url: jdbc:postgresql://localhost:5432/ytdlp
  jpa:
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true
