server:
  port: 8081

spring:
  application:
    name: ytdl
#  datasource:
#    password: password
#    username: dcat
#    url: jdbc:postgres://localhost:5432/ytdl
#  jpa:
#    properties:
#      hibernate:
#        format_sql: true
#    hibernate:
#      ddl-auto: create-drop
#    show-sql: true
