server:
  port: 0
spring:
  application:
    name: ytdlp
  datasource:
    password: password
    username: dcat
    url: jdbc:postgresql://localhost:5432/ytdlp
  jpa:
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
